### ISSUE TITLE
PARAMS not defined

### ISSUE THREAD

**Issue by rnsanchez** [hyc/mleak#1]
```
$ git b
* master 5f24d71 Cleanup

$ make
cc  -g -shared -fPIC -o mleak.so mleak.c -ldl -lunwind
cc  -g   -c -o mdump.o mdump.c
cc  -g   -c -o avl.o avl.c
cc  -g   -c -o mdname.o mdname.c
In file included from mdname.c:16:0:
demangle.h:97:16: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'PARAMS'
 cplus_demangle PARAMS ((const char *mangled, int options));
                ^
demangle.h:100:23: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'PARAMS'
 cplus_demangle_opname PARAMS ((const char *opname, char *result, int options));
                       ^
demangle.h:103:21: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'PARAMS'
 cplus_mangle_opname PARAMS ((const char *opname, int options));
                     ^
demangle.h:108:33: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'PARAMS'
 set_cplus_marker_for_demangling PARAMS ((int ch));
                                 ^
demangle.h:111:26: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'PARAMS'
 cplus_demangle_set_style PARAMS ((enum demangling_styles style));
                          ^
demangle.h:114:30: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'PARAMS'
 cplus_demangle_name_to_style PARAMS ((const char *name));
                              ^
demangle.h:118:24: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'PARAMS'
 cplus_demangle_new_abi PARAMS ((const char* mangled));
                        ^
mdname.c: In function 'md_demangle':
mdname.c:161:7: warning: assignment makes pointer from integer without a cast
   tmp = cplus_demangle(xname->name, DMGL_ANSI | DMGL_PARAMS);
       ^
<builtin>: recipe for target 'mdname.o' failed
make: *** [mdname.o] Error 1
```

**Comment by hyc** [comment]
Something wrong with your build environment. demangle.h #includes &lt;ansidecl.h&gt; which declares PARAMS.

**Comment by quanah** [comment]
@hyc fails same way with standard gcc on RHEL7

**Comment by quanah** [comment]
```
build@c7build:~/git/mleak$ grep ansidecl *
demangle.h:#include <ansidecl.h>
build@c7build:~/git/mleak$ grep PARAMS /usr/include/ansidecl.h
build@c7build:~/git/mleak$
```

**Comment by quanah** [comment]
Perhaps you are looking for: DMGL_PARAMS ?

**Comment by quanah** [comment]
I changed the code to include the system demangle.h (from binutils-devel) instead, and it compiles fine.

**Comment by quanah** [comment]
The new work still fails to compile:
```
mdname.c:17:32: fatal error: libiberty/demangle.h: No such file or directory
 #include <libiberty/demangle.h>
```

This diff works for me:
```
build@c7build:~/git/mleak$ git diff .
diff --git a/mdname.c b/mdname.c
index 1bb0ed9..5df43dd 100644
--- a/mdname.c
+++ b/mdname.c
@@ -14,7 +14,7 @@
    doesn't install it in a standard include/ directory!
    Might have to edit this include path to locate it.
    (needed for function cplus_demangle()) */
-#include <libiberty/demangle.h>
+#include <demangle.h>

 #include "avl.h"
 #include "mdump.h"
```

**Comment by quanah** [comment]
For Ubuntu16 and Debian9, demangle.h is not part of binutils-dev, instead it is in package libiberty-dev, and is the <libiberty/demangle.h>.  For older debian/ubuntu, it is part of binutils-dev, and is just <demangle.h>

**Comment by quanah** [comment]
never mind, that's a different demangle.h.  argh.

**Comment by rnsanchez** [comment]
For me (Slackware64-current as of 2017-06-28), 631e9d3838b222b9b4f7a4ca4980ab1714ee438c compiles successfully (though with a few warnings, nothing serious).

Output (gcc (GCC) 7.1.0):

    $ make
    cc  -g -fPIC -c mleak.c
    cc  -g -shared -o mleak.so mleak.o -ldl -lunwind
    g++  -g -fPIC -c mnew.cc
    mnew.cc:9:34: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     void * operator new(size_t size) throw (std::bad_alloc) {
                                      ^~~~~
    mnew.cc:15:36: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     void * operator new[](size_t size) throw (std::bad_alloc)  {
                                        ^~~~~
    g++  -g -shared -o mleak++.so mleak.o mnew.o -ldl -lunwind
    cc  -g   -c -o mdump.o mdump.c
    mdump.c: In function 'md_read_memory_trace':
    mdump.c:136:2: warning: implicit declaration of function 'close'; did you mean 'pclose'? [-Wimplicit-function-declaratio]
      close(fd);
      ^~~~~
      pclose
    mdump.c: In function 'md_read_info':
    mdump.c:161:9: warning: implicit declaration of function 'read'; did you mean 'fread'? [-Wimplicit-function-declaration]
      while (read(fd, &base, sizeof(base)) == sizeof(base)) {
             ^~~~
             fread
    mdump.c: In function 'main':
    mdump.c:187:2: warning: implicit declaration of function 'md_extract_names' [-Wimplicit-function-declaration]
      md_extract_names(0, exec);
      ^~~~~~~~~~~~~~~~
    cc  -g   -c -o avl.o avl.c
    cc  -g   -c -o mdname.o mdname.c
    cc -o mdump mdump.o avl.o mdname.o -lbfd

**Comment by hyc** [comment]
Thanks. For now I'm ignoring the mnew.cc warnings, but mdump.c should be clean now.
